### ISSUE TITLE
how does the RGB image an arrray of bytes ?

### ISSUE THREAD

**Issue by fefespn** [VulcanTechnologies/HoloLensCameraStream#10]
I want to add here:
https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanelApp.cs#L93

a condition that says if half of the pixels is red, do something ( show a hologram):
but _latestImageBytes  is an array of bytes.. so how can I code that ? 
it shouldn't be a 2-d array  (RGB)X(number of pixels) ?

**Comment by KansaiTraining** [comment]
If it is an array of BGRA bytes, this means it is similar to Format32bppArgb?

**Comment by motionsmith** [comment]
Yeah that's right, but the order of the bytes is BGRA rather than ARGB.

**Comment by SoylentGraham** [comment]
Depending on your endianess ;)
