### ISSUE TITLE
Cannot get frame samples when setting camera pixelFormat to PNG

### ISSUE THREAD

**Issue by lzhengning** [VulcanTechnologies/HoloLensCameraStream#12]
I am so thankful that you provided access to HoloLens camera stream. But I found a problem when I tried to get video frames as png format.
In the example unity project, I only changed the following line in `OnVideoCaptureCreated` of `MatrixUsageApp.cs`.
```
cameraParams.pixelFormat = CapturePixelFormat.PNG;
```
Then I found that `OnFrameSampleAcquired` was never called. 
Is there something else I have to change?

**Comment by SoylentGraham** [comment]
I am 80% sure I read in some docs, or a forum post (on the microsoft hololens forums) that PNG isn't supported on this device, but I cannot find it at all, so I may be thinking of something else.

Does JPEG work?

**Comment by lzhengning** [comment]
I tested all of the provided format. BGRA32 and NV12 work well while JPEG and PNG don't.

By the way I used to use photo capture in HoloLens's locatable camera. It supports JPEG and PNG. Maybe photo capture is different from video frame capture.

**Comment by SoylentGraham** [comment]
aha yes! That's definitely correct, I just can't find the docs on it (but it IS documented somewhere) that it doesn't allow encoding on video capture (aside from the NV12->BGRA)

**Comment by JorisWilligEttu** [comment]
Am I correct in assuming then that this does not work for JPEG either?
