### ISSUE TITLE
get error on Unity

### ISSUE THREAD

**Issue by seonjoo1031** [VulcanTechnologies/HoloLensCameraStream#14]
Hi
First thank you so much for contributing the code.
I want to apply OpenCV on image from Hololens camera for object recognition and I found your code.
While trying to running sample, I encountered this error.
![image](https://cloud.githubusercontent.com/assets/22390418/26812914/a950daf6-4ab5-11e7-8f41-e509124948ce.png)
Then, should I install this package manually?
or did I miss something?
(I opened the unity project, was trying to import HoloLensCameraStream unity package into the project and got the error)
I'm looking forward to your reply.
Thanks.

**Comment by sanidhya26** [comment]
hey, how did you solve it?..did you install the package?
