### ISSUE TITLE
VideoCaptureSample.CopyRawImageDataIntoBuffer() byte sequence rotated by 180 degrees returns mirrored

### ISSUE THREAD

**Issue by labellson** [VulcanTechnologies/HoloLensCameraStream#15]
Hey there,
First of all, thanks for this amazing plugin. I made some tests with it in the VideoPanelExample.
I've been playing with this line of code of [VideoPanelApp](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanelApp.cs#L74)
```
cameraParams.rotateImage180Degrees = true; //If your image is upside down, remove this line.
``` 

The line below decides the value of rotation property in [VideoCapture](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensCameraStream/Plugin%20Project/VideoCapture.cs#L253)

The issue appears if `rotateImage180Degrees = true` because the property is applied and the byte sequence returned is rotated by 180 and mirrored.

![hololens_pic_of_pic_mirrored](https://user-images.githubusercontent.com/4384330/26981562-d67cf488-4d35-11e7-93f1-75b805ac23f5.jpg)

If `rotateImage180Degrees = false`, the byte sequence returns without any rotation, but upside-down.

![hololens_pic_norotated](https://user-images.githubusercontent.com/4384330/26982833-fe1bea90-4d39-11e7-9bde-f14a1713171c.jpg)

I think, mirroring horizontally the byte sequence would be the best way to solve the issue, but I haven't found a way to achieve this in the MediaCapture documentation.

A possible workaround would do it manually outside the plugin.
```
private byte[] mirrorByteBufferHorizontally(int width, byte[] b)
{
        wisdth *= 4;
        byte[] _b = new byte[width];
        for (int i = 0, j = b.Length - width; i < j; i += width, j -= width)
        {
            Array.ConstrainedCopy(b, i, _b, 0, width);
            Array.ConstrainedCopy(b, j, b, i, width);
            Array.ConstrainedCopy(_b, 0, b, j, width);
        }

        return b;
}
```

**Comment by SoylentGraham** [comment]
As it's not clear what the GUID's for other properties are (a matrix property would be perfect) - see docs on the rotation guid; https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/handle-device-orientation-with-mediacapture - yeah, some manual intervention would be needed.

The FASTEST (may not be the "best" for your case) way to deal with this would be to transform it in a shader at render time, not by changing the bytes directly...

But yeah, with or without rotate180, the pixels are mirrored....

Although now I think about it, I don't think they're mirrored in my app. Is it possible one of us is rendering the texture backwards? (might be me :)

**Comment by motionsmith** [comment]
I'm not positive why the image appears mirrored, but I read in Microsoft's documentation (I don't remember where) that they expect developers to mirror the feed in the view component. My guess is that doing so in the view allows the GPU to do this more efficiently than having the CPU flip the pixels one-by-one (or n-by-n if you parallelize it). 

Feel free to suggest how to label this issue. :)

**Comment by labellson** [comment]
You are right. Without a property to mirror the bytes. The best way might be leaving it as it is.

Feel free to close the issue if you think so :D

**Comment by SoylentGraham** [comment]
There could be a function to enumerate all the property guids. I don't think MediaFoundation had this, but the effects do...

**Comment by lyziew** [comment]
Just set scale x=-1 you can get right view

**Comment by SoylentGraham** [comment]
> Just set scale x=-1 you can get right view

There is no scale.

**Comment by labellson** [comment]
> Just set scale x=-1 you can get right view

I've mirrored the texture in a [shader](https://github.com/labellson/HoloLensCameraStream/blob/2d9ef7d355b2bd4da3ae0c2281677b1dfd1d959b/HoloLensVideoCaptureExample/Assets/Resources/Shaders/HolographicImageBlend.shader#L76)

**Comment by KansaiTraining** [comment]
> I've mirrored the texture in a shader

I am sorry for the basic question but where do I put this shader? 
I am super beginner in Unity :(
