### ISSUE TITLE
NotImplementedException: The requested feature is not implemented

### ISSUE THREAD

**Issue by andreeabir** [VulcanTechnologies/HoloLensCameraStream#17]
Hello,

When I want to try the VideoPanel example I get this error in Unity: NotImplementedException: The requested feature is not implemented.
HoloLensCameraStream.VideoCapture.CreateAync (HoloLensCameraStream.OnVideoCaptureResourceCreatedCallback onCreatedCallback)
CameraStreamHelper.Awake () (at Assets/CamStream/Scripts/CameraStreamHelper.cs:88).
When I try the solution in Visual Studion on Local Machine in the Debug Console show:
"Creating the VideoCapture object failed."
What is the problem and how can I solve it? 
Mention that I have version 5.6 of Unity and I follow all the steps in the readme.
Thank you :)

**Comment by SoylentGraham** [comment]
The functionality has not been implemented on non-UWP devices. (ie. windows/osx editor)

The plugin only works on the device, but stub implementations are there so that it compiles still.
