### ISSUE TITLE
Make locatable camera attributes useful to Unity

### ISSUE THREAD

**Issue by motionsmith** [VulcanTechnologies/HoloLensCameraStream#2]
The locatable camera attributes that come with the frame sample are returned as raw byte arrays and are not usable in the Unity world coordinate system. The `viewTransform` and `projectionTransform` can be used to map 2D pixel locations to 3D points in space (and vice versa), but not as they are currently.

Some research needs to be done to understand how to accomplish this.

**Comment by Zod-** [comment]
Any clue where to begin with this? I've used your example to process each frame with UWPs [FaceTracker](https://docs.microsoft.com/en-us/uwp/api/windows.media.faceanalysis.facetracker) and now I'd like to translate the face locations into Unitys coordinate system.

**Comment by motionsmith** [comment]
You'll want to get the [transformation matrix](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensCameraStream/Plugin%20Project/VideoCaptureSample.cs#L128) and the [projection matrix](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensCameraStream/Plugin%20Project/VideoCaptureSample.cs#L148), available with each image sample.

You'll need a good understanding of the stuff [in this article about the locatable camera](https://developer.microsoft.com/en-us/windows/mixed-reality/locatable_camera).

Some transformation may be necessary to make the above matrices compatible with Unity's coordinate system. Once that is done properly, I think we would have parity with the matrices that are available with Unity's PhotoCapture API.

We could then learn from [the stuff Brandon Fogerty did here](https://forum.unity3d.com/threads/locatable-camera-in-unity.398803/) to verify that the frames are positioned correctly via the matrices. 

Finally, I've had some success following [CurvSurf's suggestions in this thread](https://forums.hololens.com/discussion/3117/pixel-coordinates-to-world-coordinates) for converting a pixel coordinate to a world coordinate.

I hope this helps!
