### ISSUE TITLE
Video camera data output

### ISSUE THREAD

**Issue by zach5410** [VulcanTechnologies/HoloLensCameraStream#21]
Hey everyone,

I am working on a project that requires me to analyze each video frame captured from the Hololens.  However, when I look at the image data it can only be uncompressed and when I try to change to a compressed format (JPEG/PNG) the video camera will not start.

My Questions:
What format is the uncompressed data in?  I tried BGRA and NV12 and neither of those were readable for me in Unity or OpenCV.  

Is there a reason as to why when I compress the data the video is prevented from starting?

Thank you
~Zach

**Comment by SoylentGraham** [comment]
It’s definitely in a 4 component (one byte each) BGRA format.

You’re correct, the video doesn’t come through if set to jpeg/png.

My project took the BGRA data (32 bits per pixel) and compressed it to jpeg

How were you trying to use the data or transfer it to opencv?

**Comment by syalanurag1991** [comment]
How did you compress it to JPG. My HoloLens hands if I use "EncodeToJPEG" method in Unity.

**Comment by SoylentGraham** [comment]
I wrote a plugin in c/++ so I could do it in another thread. 
I'm pretty sure I open sourced it "PopEncodeJpeg"

**Comment by codec-abc** [comment]
Why this issue was closed since the library has a JPEG output format that does not work at all?

**Comment by SoylentGraham** [comment]
> Why this issue was closed 
Closed because the original question was answered?

> since the library has a JPEG output format that does not work at all?
Microsoft's jpeg output format doesn't work. This library doesn't have jpeg output.
