### ISSUE TITLE
Performance crash after using videostream

### ISSUE THREAD

**Issue by DineshPunni** [VulcanTechnologies/HoloLensCameraStream#23]
Hi,
i love your asset. It works perfectly fine and i could integrate it to my project.
However, once i open the videostream the app runs really slow.
I already tried to disable the video panel and camera stream gameobject. 
I also disabled the video panel app script on the main camera.
But even after this the app runs really slow.

Is there any way to keep the performance high after using the video stream?

Thanks,
Dinesh

**Comment by SoylentGraham** [comment]
Hololens (the OS) throttles the frame rate to 30fps from 60 whenever the camera is enabled... Could this be what you're seeing?
