### ISSUE TITLE
What is the size of the Image?

### ISSUE THREAD

**Issue by KansaiTraining** [VulcanTechnologies/HoloLensCameraStream#25]
I am reading the code of MatrixUsageApp and I can see that the byte[] array that contains the image is a one dimensional array. The size of it is obtained through `sample.dataLength`  where sample is a `VideoCaptureSample`

Reading the code of VideoCaptureSample I notice that I can get the total size of the data (with dataLength) but how can I get the Height and Width (in pixels) of the image?? I need this to do 2D processing.

**Comment by SoylentGraham** [comment]
You provide the resolution when you start capturing. See `CameraParameters`. The callback in `CreateAync` also gives you access to the resoltuion and framerate

https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanelApp.cs#L69
Here is an example of where you can see what resolution of the stream is you created
