### ISSUE TITLE
How do I actually get a frame?

### ISSUE THREAD

**Issue by JorisWilligEttu** [VulcanTechnologies/HoloLensCameraStream#30]
This might be a stupid question, but how do I actually use this? I call videoCapture.StartVideoModeAsync and... That is where I'm stuck. Any help would be greatly appreciated

**Comment by SoylentGraham** [comment]
In the example, you setup a stream, then add a listener to the event triggered when a new frame arrives (which may not be on the mono/main thread)
https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanelApp.cs#L65

That callback function has a structure with the bytes of the frame
https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanelApp.cs#L93

Which you can do what you like with...

Is there any specific point where you're stuck? Is there anything in the example that doesn't make sense?

**Comment by JorisWilligEttu** [comment]
Gotcha, I didn't actually find the example... :S It's all clear now, thanks!
