### ISSUE TITLE
Could not deploy code to HoloLens

### ISSUE THREAD

**Issue by istiaqMahbub** [VulcanTechnologies/HoloLensCameraStream#31]
I have to implement something that's how to access the camera of HoloLens and send the video stream to PC side. According to the mentioned step, I do the same step. I just build the project and do not change anything in the DLL file. Because I just want to run the example project at first. So, for this at first, I build the plugin, at that time I also setup missing NuGet packages. Then I jump to "Running the example Unity Project". in Unity, there's no problem with building the SDK and other parameters. 

Now, go for VS solution, setting the deploy (ARM to x86, Device) and when I start to debug and deploy the code to HoloLens, at that time there has an error generated in Visual Studio.

![error](https://user-images.githubusercontent.com/26251743/34778849-cb36560e-f61e-11e7-9334-62893264e771.PNG)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error The command ""C:\unity\Hololens\App\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="C:\unity\Hololens\App\Hololens\project.lock.json" -bits=32 -configuration=Debug -removeDebuggableAttribute=False -uwpsdk=10.0.16299.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Debug" "C:\unity\Hololens\App\Hololens\Assembly-CSharp.dll" "C:\unity\Hololens\App\Hololens\Assembly-CSharp-firstpass.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.Analytics.dll" "C:\unity\Hololens\App\Hololens\nunit.framework.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.UI.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.HoloLens.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.Networking.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.VR.dll"" exited with code 1.	Hololens	C:\unity\Hololens\App\Hololens\Hololens.csproj	282	
```

Now, I'm stuck with this. Could you please help me to solve this? Please tell me what I could and how I could solve it. For your info, I also attached this image. 

For your info, I want to mention that I use Unity Version: 5.6.0f3 and the Visual Studio 's version is: Visual studio community 2017 .

**Comment by SoylentGraham** [comment]
Is there more information in the output tab?

**Comment by istiaqMahbub** [comment]
For your info, I give it to here
```
1>------ Build started: Project: Assembly-CSharp-firstpass, Configuration: Debug x86 ------
1>  Running SerializationWeaver...
1>  Symbols will be read from C:\unity\Hololens\App\Hololens\Unprocessed\UnityEngine.pdb
1>  Symbols will be read from C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Unprocessed\Assembly-CSharp-firstpass.pdb
1>  WeaveAssemblies unityPath= C:\unity\Hololens\App\Hololens\Unprocessed\UnityEngine.dll
1>  WeaveAssemblies unetPath= C:\unity\Hololens\App\Hololens\Unprocessed\UnityEngine.Networking.dll
1>  Symbols will be read from C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Unprocessed\Assembly-CSharp-firstpass.pdb
1>  Script Module: Assembly-CSharp-firstpass.dll
1>  Pass: 0 took 0 milliseconds
1>  Pass: 1 took 3 milliseconds
1>  Symbols will be read from C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Unprocessed\Assembly-CSharp-firstpass.pdb
1>  Weaving assembly C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Unprocessed\Assembly-CSharp-firstpass.dll
1>  Will export symbols of pdb format
1>  SerializationWeaver done.
1>  Assembly-CSharp-firstpass -> C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp-firstpass\bin\x86\Debug\Assembly-CSharp-firstpass.dll
2>------ Build started: Project: Assembly-CSharp, Configuration: Debug x86 ------
2>  Running SerializationWeaver...
2>  Symbols will be read from C:\unity\Hololens\App\Hololens\Unprocessed\UnityEngine.pdb
2>  Symbols will be read from C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Unprocessed\Assembly-CSharp.pdb
2>  WeaveAssemblies unityPath= C:\unity\Hololens\App\Hololens\Unprocessed\UnityEngine.dll
2>  WeaveAssemblies unetPath= C:\unity\Hololens\App\Hololens\Unprocessed\UnityEngine.Networking.dll
2>  Symbols will be read from C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Unprocessed\Assembly-CSharp.pdb
2>  Script Module: Assembly-CSharp.dll
2>  Pass: 0 took 22 milliseconds
2>  Pass: 1 took 15 milliseconds
2>  Symbols will be read from C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Unprocessed\Assembly-CSharp.pdb
2>  Weaving assembly C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Unprocessed\Assembly-CSharp.dll
2>   + VideoPanel
2>   + VideoPanelApp
2>   + CameraStreamHelper
2>  Will export symbols of pdb format
2>  SerializationWeaver done.
2>  Assembly-CSharp -> C:\unity\Hololens\App\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Assembly-CSharp.dll
3>------ Build started: Project: Hololens, Configuration: Debug x86 ------
3>C:\unity\Hololens\App\Hololens\App.cs(56,13,56,71): warning CS0618: 'ApplicationView.SuppressSystemOverlays.set' is obsolete: 'Use the TryEnterFullScreen method and IsFullScreenMode property instead of SuppressSystemOverlays. For more info, see MSDN.'
3>  Hololens -> C:\unity\Hololens\App\Hololens\bin\x86\Debug\Hololens.exe
3>  UnityWSAPlayerDir "C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\".
3>  UnityProjectDir "C:\unity\Hololens\".
3>  Copying unprocessed assemblies...
3>  Running AssemblyConverter...
3>  System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
3>     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
3>     at UnityEditor.Scripting.Compilers.NuGetPackageResolver.Resolve()
3>     at Unity.UWPAssemblyResolver..ctor(String projectLockFile, String desiredUWPSDKVersion)
3>     at Unity.OperationContext.SetPlatform(Platform platform, String projectLockFile, String uwpSDK)
3>     at Unity.ParseArgsStep.Execute()
3>     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
3>     at Unity.Operation.Execute()
3>     at Unity.Program.Main(String[] args)
3>C:\unity\Hololens\App\Hololens\Hololens.csproj(282,9): error MSB3073: The command ""C:\unity\Hololens\App\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="C:\unity\Hololens\App\Hololens\project.lock.json" -bits=32 -configuration=Debug -removeDebuggableAttribute=False -uwpsdk=10.0.16299.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Debug" "C:\unity\Hololens\App\Hololens\Assembly-CSharp.dll" "C:\unity\Hololens\App\Hololens\Assembly-CSharp-firstpass.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.Analytics.dll" "C:\unity\Hololens\App\Hololens\nunit.framework.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.UI.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.HoloLens.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.Networking.dll" "C:\unity\Hololens\App\Hololens\UnityEngine.VR.dll"" exited with code 1.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by SoylentGraham** [comment]
hmm, I'm not sure what that exact issue is, (Not sure if it's related to this plugin or not), but one note is that when you deploy any project to hololens, I believe it has to be a `release` and not `debug` configuration (although I could be wrong, it's been a while since I've debugged an app)

I assume you have no problems deploying an empty unity project?

**Comment by istiaqMahbub** [comment]
Please check the link for deploy the code to HoloLens "https://developer.microsoft.com/en-us/windows/mixed-reality/using_visual_studio". In here they mentioned that Debug > Start Debugging. 

In previous, I also deploy other own build apps in this way. 

In this project, there have 3 projects. Hololens, Assmbely-CSharp and Assembely-CSharp-firstpass. Between them, 2 are passed but the problem arises in a single project.

**Comment by SoylentGraham** [comment]
It LOOKs like it might be the same as these issues. (incompatible visual studio version)
https://forum.unity.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/
https://www.codeproject.com/Articles/1203935/Resolving-build-issues-for-UWP-packages-with-Unity


Does an empty unity project deploy? This will help identify if your problem is related to this plugin/assembly or just your own setup.

**Comment by SoylentGraham** [comment]
Also, I think you misunderstood my comment about the build CONFIGURATION. `Debug` -> `Start debugging` are the menu commands, not the build configuration. As the link you sent shows, they use `Master` not `Debug`
![image](https://user-images.githubusercontent.com/2184197/34781351-82545cc0-f61d-11e7-9763-f59086b619bf.png)

**Comment by istiaqMahbub** [comment]
There has no problem to deploy an empty Unity project to HoloLens.

According to the version of Visual Studio, I used 15.5.0. But in your mentioned link, they used 15.3.3. For Unity, I used 5.6.0f3. Should I go for 2017 version?

**Comment by motionsmith** [comment]
I've seen this error before, but I don't remember what the problem was anymore. Try reading this thead and see if you need to patch Unity or maybe upgrade visual studio.

https://forum.unity.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/

**Comment by motionsmith** [comment]
@istiaqMahbub I tested the latest version of Visual Studio, and it works correctly with the latest version of Visual Studio.

**Comment by istiaqMahbub** [comment]
@motionsmith : Could you please tell me which version of Unity and Visual Studio you used? Still now, I am stuck with the problem. And could you please also mention me which missing package I need to install?  I follow the same step which you mentioned in your document. But so far, the problem has existed. 

So, if you tell me which version, I need to be used for build the code and deploy it to HoloLens. Hope you will help me to solve this problem.

**Comment by MaXvanHeLL** [comment]
@istiaqMahbub : I get the same error message using Unity 2017 and Visual Studio 2017. Tried both branches of the HoloLensCameraStream, namely the original for Unity 5 and the (almost) fully upgraded one for Unity 2017. However, the error occurs on both versions for me.

Any updates on that particular issue?

**Comment by MaXvanHeLL** [comment]
@istiaqMahbub: okay I am pretty sure the problem was due to an older Unity Version. I tried with 2017.2 before and I got the same error. Once I upgraded to 2017.3 the assembly error did not show up anymore. However, an exception occured on InvokeOnAppThread() in VideoPanelApp.cs. So appearantly something is wrong with the threading. A quick fix is outcommenting the following codeline (~77) in VideoPanelApp.cs:

// UnityEngine.WSA.Application.InvokeOnAppThread(() => { _videoPanelUI.SetResolution(_resolution.width, _resolution.height); }, false);

and exchange it with:

_videoPanelUI.SetResolution(_resolution.width, _resolution.height);

The VulcanTechnology HoloLemsCameraStream Project works now for me (except for the projection sample).

Best,

**Comment by motionsmith** [comment]
We're using it with projects on Unity 5.6.5f1 and 2017.2.1f1 and with the latest version of visual studio. The I think the SerializationWeaver problem goes away if you delete your Build (App) folder and regenerate it.

@MaXvanHeLL Yes, `InvokeOnAppThread` doesn't work anymore on the newer versions of Unity. I made a branch that successfully upgrades HoloLensCameraStream to Unity v2017.3. Check it out [here](https://github.com/VulcanTechnologies/HoloLensCameraStream/tree/unity20173upgrade). You can see from the changelist that I ended up making my own version of InvokeOnAppThread that should be threadsafe (it's not really tested).

**Comment by eco3** [comment]
@motionsmith I downloaded your branch you suggested and even switched up the line of code, @MaXvanHeLL included. Still I get the same error as @istiaqMahbub 

I'm using Unity 2017.3.1f1 and Visual Studio 15.3.2

**Comment by motionsmith** [comment]
Hah, wow that's good to know @eco3. Hopefully this will be helpful to others.
