### ISSUE TITLE
Mirrored Video Feed

### ISSUE THREAD

**Issue by christjt** [VulcanTechnologies/HoloLensCameraStream#34]
First of all, great work on this Camera Stream provider. Everything is working really well!

I have seen in some previously closed issues that there has been som problems with the video feed being mirrored. This also seems to be the case for me, and I cannot find a fix for it. By enabling the rotate180degrees flag, it is indeed not upside-down anymore, but the left part of the image is shown on the right side etc. This poses problems for me as I am trying to use it for pattern recognition(tracking real world position of a pattern).

I saw some of the resources linked in #1 but I trouble implementing it. Any ideas? (I know I can simply swap the bytes from the resulting image, but this seems terribly inefficient...)

Thanks!

**Comment by motionsmith** [comment]
Thanks @christjt. Yes, you could swap the bytes and it would be slower than some other methods, but might be suitable depending on your needs.

I don't have much experience writing GPU processes, but it could be done efficiently there. The Projection Sample does this, I believe. If you're displaying the frames, then an easy way is to swap the UVs on the quad that you are rendering the frame onto.

If you're doing some CV analysis or pixel-to-world projection, take a look at the Projection Sample.

**Comment by christjt** [comment]
Thanks @motionsmith, I will simply have to swap the bytes I think. I am sending the image data to OpenCV which then gives me information about certain positions of markers found in the image. If the image is mirrored, then the results will obviously be wrong. 

Thanks for help though!

**Comment by motionsmith** [comment]
I wonder if OpenCV has an efficient function for mirroring. Seems like it would.

**Comment by SoylentGraham** [comment]
Really, you wouldn't mirror the image, send it to opencv and just reverse the results! :) (Depending on what you're doing of course, fine for feature matching, finding homographies etc)
Ideally if opencv performs some other transform (lens correction, warping, fisheye undistortion etc, you'd put the mirroring in whatever transformation matrix there is there)

**Comment by christjt** [comment]
@SoylentGraham Seems like the best solution! should be able to play with the cameraToWorld matrix such that it fixes this.
