### ISSUE TITLE
Holotoolkit is having issues in 5.6 (heads up)

### ISSUE THREAD

**Issue by MustacheEmperor** [VulcanTechnologies/HoloLensCameraStream#5]
Hey there,

Just found this project today - looks awesome. Will aim to contribute once I figure out how.

I noticed the project is built in 5.6 and wanted to give you a word of warning that there seems to be something messed up in the WorldAnchor system in HoloToolkit in 5.6. I encountered some very odd behavior losing worldanchors and failing builds from visual studio with a different project I upgraded and found some forum threads online with similar problems. The Holotoolkit doesn't officially support 5.6 yet so I believe that is why.

**Comment by MustacheEmperor** [comment]
This project doesn't actually make use of holotoolkit, so I'm going to close this issue.

**Comment by motionsmith** [comment]
Thanks @MustacheEmperor. You're right HoloToolkit isn't a dependency (I tried to keep all dependencies out), however I personally consider HoloToolkit effectively a practical dependency for any HL project. Hopefully their issues with 5.6 will close soon.

**Comment by MustacheEmperor** [comment]
@motionsmith Yeah, I figured I'd warn you since it causes some nasty issues. 5.6 support is supposed to be in the next HoloToolkit release, fortunately.

Great to find someone else actively working on these challenges on Hololens. I'll drop you a note from my work email so we can keep in communication.
