### ISSUE TITLE
Unity 2018.2 IL2CPP support

### ISSUE THREAD

**Issue by christjt** [VulcanTechnologies/HoloLensCameraStream#52]
Hello,

I have been working recently on trying to get this working on 2018.2 using IL2CPP since .NET is being deprecated. To make things easier for myself untangled the dlls and wrapped it in compiler directives. But for some reason I can not, for the life of me get, past this "No capture devices available" when initializing the MediaCapture. I tried dumbing it down as much as possible into:

```cs

var allFrameSourceGroups = await MediaFrameSourceGroup.FindAllAsync();

        var candidateFrameSourceGroups = allFrameSourceGroups.Where(group => group.SourceInfos.Any((a) => a.SourceKind == MediaFrameSourceKind.Color && a.MediaStreamType == MediaStreamType.VideoPreview));
        var selectedGroup = candidateFrameSourceGroups.First();

        _mediaCapture = new MediaCapture();

        var mediaCaptureInitSettings = new MediaCaptureInitializationSettings()
        {
            SourceGroup = selectedGroup,
            SharingMode = MediaCaptureSharingMode.ExclusiveControl,
            MemoryPreference = MediaCaptureMemoryPreference.Cpu,
            StreamingCaptureMode = StreamingCaptureMode.Video
        };

        try
        {
            await _mediaCapture.InitializeAsync(mediaCaptureInitSettings);
        }
        catch (Exception e)
        {
            Debug.Log("Camera initialization failed: " + e.Message);
        }
```

But using il2cpp just really brakes the ability to run ```InitializeAsync()```. Starting to suspect that there is a Unity bug going on here. Any tips?

**Comment by achaperon** [comment]
Hello, we noticed that the retrieve of Matrix4x4 using the C# command "as" return null when converted by IL2CPP.
To correct this we made our own translation using Marshalling and unmanaged/managed call.
But apparently Unity has fixed the translation of arrays with IL2CPP on the Unity Editor 2018.2.16.
You should update your editor version, it fixes a lot of issues regarding IL2CPP.
Regards.

**Comment by christjt** [comment]
Yup, upgrading to .16 fixed the issue.
