### ISSUE TITLE
Does the plugin work in research mode?

### ISSUE THREAD

**Issue by Aimi-no** [VulcanTechnologies/HoloLensCameraStream#62]
Hi,
I'm currently trying to make an Unity app that works with HoloLens streams, so I work with the research mode enabled. I currently have issues with getting the stream from the POV camera and I found your plugin that could help me. I could find anywhere mentioned if it works in research mode as well so I am asking before trying it.
Thank you.

**Comment by doughtmw** [comment]
Here is a [sample project](https://github.com/doughtmw/HoloLensForCV-Unity) which makes use of the short-throw time-of-flight depth camera (research stream) and photo-video camera streams in Unity through IL2CPP build support.

**Comment by Aimi-no** [comment]
Thank you so much, that helped.
