### ISSUE TITLE
Image is a mirror? (How to flip on y-axis)

### ISSUE THREAD

**Issue by YizeD** [VulcanTechnologies/HoloLensCameraStream#66]
When I run the videopanel example, the image displayed is a mirror image. I'm trying to stream the images quickly over a network, so I would prefer not to have to flip the image pixel by pixel before converting to a jpg. Is there a setting that let's the HoloLens camera take an image without flipping the y-axis?

**Comment by lapislazinus** [comment]
The image obtained from the camera stream should have its origin in the top-left corner, with the x-axis going to the right and the y-axis down like [this](https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/manuals_clip0138_zoom69.png)
Unity texture coordinate system has its origin at the bottom-left corner with the x-axis going up.

Check what coordinate system your jpg conversion algorithm expects, if you need to flip i think someone posted C# code somewhere here

**Comment by YizeD** [comment]
Got it, thanks! As long as it's just Unity acting weird, then I don't really mind since I'm putting it together on the other end without using Unity.
