### ISSUE TITLE
Hololens streaming in Android

### ISSUE THREAD

**Issue by einstyle** [VulcanTechnologies/HoloLensCameraStream#9]
Hi,
I mean, I have to build an Android app that streams Hololens video. 
Is it possible with that code? Any suggestions?

**Comment by SoylentGraham** [comment]
This code enables you to do the first part of video streaming. My suggestion would be to research how to stream video.

The process is essentially as follows;
`Video feed -> Pixel data -> Encode frame to jpeg/h264/etc -> Send to server/client -> Receive on client -> decode to pixels -> draw to screen/texture/etc`
This project allows you to do the first & second part on hololens. The rest is up to you how you want to do it. There are 100's of ways to do it, depending on your needs (latency, quality, network usage, encoder/decoder speed, clients)

**Comment by einstyle** [comment]
What do you mean for first and second part exactly? video feed and pixel data?
I've tried right now to execute this project but when I run it on Hololens it gives me a white screen. What does it mean? Maybe I forgot some settings?
Here a screenshot.

![image](https://cloud.githubusercontent.com/assets/9775365/25533177/0519ea5c-2c30-11e7-8244-30d63e461eba.png)

**Comment by motionsmith** [comment]
I would recommend looking at [this repo from Microsoft](https://vulcan.atlassian.net/wiki/display/FOR/Mouse+of+Life). This, I believe, has the end-to-end support that @SoylentGraham referred to.

**Comment by einstyle** [comment]
Hi,
Thank you for the reply.
The link refers to vulcan.atlassian.net and need user and password to login. Can I register?

**Comment by SoylentGraham** [comment]
> What do you mean for first and second part exactly? video feed and pixel data?
I've tried right now to execute this project but when I run it on Hololens it gives me a white screen. What does it mean? Maybe I forgot some settings?
Here a screenshot.

What you've shown in the screenshot is essentially the "Icon" for your app on the hololens "desktop". If you click it, your app will launch!

**Comment by motionsmith** [comment]
Sorry @einstyle I meant [this link](https://github.com/Microsoft/HoloLensCompanionKit/tree/a5615d18b8e1dc1a59af5b591ebca87e8f1aa648/MixedRemoteViewCompositor). Hopefully that link works. :)

**Comment by einstyle** [comment]
@SoylentGraham I clicked on the window but nothing appears. Instead, the application will load again with a white screen... 
@motionsmith  Thank you for the link! I will look there

**Comment by motionsmith** [comment]
@einstyle I think, if the app is running in a Window, rather than "full screen", it's usually a publish settings issue. [Try reviewing this tutorial](https://developer.microsoft.com/en-us/windows/mixed-reality/holograms_100) against your app and make sure all those settings are properly configured for you.

**Comment by einstyle** [comment]
Thank you @motionsmith , I'm going to take a look at the tutorial. I will let you know

**Comment by fefespn** [comment]
where i the code i can take the data from the camera ?
I need to do this if anyone can help:
1- get data
2-  process it (faceDetection)
3- display hologram around the face

**Comment by SoylentGraham** [comment]
@fefespn 

> where in the code i can take the data from the camera ?
> I need to do this if anyone can help:
> 1- get data
> 2- process it (faceDetection)
> 3- display hologram around the face

The example code shows you how to get and use the data
https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanelApp.cs#L86

You should probably start a new issue if your face detection issue, is a different issue to "how to stream to android"

**Comment by SoylentGraham** [comment]
@einstyle I am working on a commercial solution for streaming to other devices (android included). If you're interested in this you can contact me privately; graham@newchromantics.com
